jenkins:
  agentProtocols:
    - 'JNLP4-connect'
    - 'Ping'
  slaveAgentPort: 50000
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  remotingSecurity:
    enabled: true
  numExecutors: ${JENKINS_MASTER_EXECUTORS}
  quietPeriod: ${JENKINS_QUIET_PERIOD}
  scmCheckoutRetryCount: ${JENKINS_SCM_RETRY_COUNT}
  labelString: master
  mode: EXCLUSIVE


markupFormatter:
  rawHtml:
    disableSyntaxHighlighting: false 
  
unclassified:
  location:
    adminAddress: ${JENKINS_ADMIN}
    url: ${JENKINS_URL}