jenkins:
  agentProtocols:
    - 'JNLP4-connect'
    - 'Ping'
  slaveAgentPort: 50000
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  remotingSecurity:
    enabled: false

security:
  remotingCLI: 
    enabled: false

unclassified:
  location:
    adminAddress: ${JENKINS_ADMIN}
    url: ${JENKINS_URL}